name: CI

on:
  pull_request:
    branches: [ main ]

jobs:
  run-test:
    name: 'Run tests'
    runs-on: ubuntu-latest

    steps:
      - name: Clone Project
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: Install Requirements
        run: pip install -r requirements.txt

      - name: Run Tests
        run: python -m pytest tests